FROM postgres:9.6

COPY ./db/create_db_docker.sh /docker-entrypoint-initdb.d/
# Remove windows \r linefeed in shellscript using dos2unix
RUN apt-get update && apt-get install -y dos2unix
RUN dos2unix /docker-entrypoint-initdb.d/create_db_docker.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

COPY ./db/database_schema.schema /docker-entrypoint-initdb.d/
COPY ./db/municipalities_import.csv /docker-entrypoint-initdb.d/
COPY ./db/object_types_import.csv /docker-entrypoint-initdb.d/